version: '3.8'

services:
#  app:
#    build: .
#    ports:
#      - "5000:5000"
#    environment:
#      - FLASK_APP=run.py
#      - FLASK_ENV=production
#      - PORT=5000
#      - DATABASE_URL=sqlite:///ddos_detection.db
#      - REDIS_URL=redis://:root123@redis:6379/0
#    volumes:
#      - ./instance:/app/instance
#    depends_on:
#      - redis
#    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass root123
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
